# Ocean Data Sources Configuration
# Defines data sources, URLs, and processing parameters for each dataset

datasets:
  sst:
    name: "NOAA OISST v2.1"
    description: "Sea Surface Temperature - Optimum Interpolation"
    base_url: "https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/"
    file_pattern: "oisst-avhrr-v02r01.{date}.nc"
    url_pattern: "{base_url}{year_month}/oisst-avhrr-v02r01.{date}.nc"
    temporal_coverage:
      start: "1981-09-01"
      end: "present"
      test_start: "2024-01-01"  # Start with 2024 for testing
    spatial_resolution: 0.25  # degrees
    target_resolution: 1.0    # downsample to 1 degree
    coordinate_system: "0-360"  # needs conversion to -180-180
    variables: ["sst", "anom", "err", "ice"]
    update_frequency: "daily"
    file_size_mb: 1.6  # approximate size per file
    processing:
      downsample: true
      harmonize_coords: true
    
  waves:
    name: "CMEMS Global Waves Analysis and Forecast"
    description: "Global Ocean Waves Analysis and Forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_WAV_001_027"
    dataset_id: "cmems_mod_glo_wav_anfc_0.083deg_PT3H-i"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "1993-01-01"
      end: "present"
      test_start: "2024-01-01"
    spatial_resolution: 0.083  # 1/12 degrees
    coordinate_system: "-180-180"
    variables: ["VHM0", "VMDR", "VTPK"]  # significant height, direction, period (actual CMEMS names)
    update_frequency: "daily"
    file_size_mb: 25  # approximate size per file
    processing:
      harmonize_coords: false  # already in -180-180
    credentials_required: true
    
  currents:
    name: "CMEMS Global Ocean Currents"
    description: "Global Ocean Physics Analysis and Forecast - Currents"
    product_id: "GLOBAL_ANALYSISFORECAST_PHY_001_024"
    dataset_id: "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2022-06-01"  # Updated based on CMEMS dataset availability
      end: "present"
      test_start: "2024-01-01"
    spatial_resolution: 0.083  # 1/12 degree
    coordinate_system: "-180-180"
    variables: ["uo", "vo"]  # zonal and meridional velocity
    layers: ["surface"]  # Phase 1: surface only
    update_frequency: "daily"
    file_size_mb: 15  # approximate size per file
    processing:
      harmonize_coords: false
    credentials_required: true
    
  # STRATEGIC HYBRID APPROACH: GLODAP + CMEMS
  # Combines discrete pH measurements from GLODAP with continuous daily nutrients from CMEMS
  
  glodap_ph:
    name: "GLODAP Global Ocean pH Observations (1993-2021)"
    description: "Historical discrete pH measurements from Global Ocean Data Analysis Project"
    product_id: "INSITU_GLO_BGC_CARBON_DISCRETE_MY_013_050"
    dataset_id: "cmems_obs-ins_glo_bgc-carbon_my_glodap_irr"
    base_url: "https://data.marine.copernicus.eu"
    data_portal_url: "https://www.ncei.noaa.gov/data/oceans/ncei/ocads/metadata/0162565.html"
    temporal_coverage:
      start: "1993-01-01"
      end: "2021-12-31"
      test_start: "1993-01-01"
    spatial_resolution: "1.0° gridded climatologies + discrete bottle samples"
    coordinate_system: "-180-180"
    variables: ["ph", "ph_insitu", "ph_insitu_total", "talk", "dic", "pco2", "revelle"]
    data_type: "discrete_samples"  # Key difference from CMEMS
    update_frequency: "cruise_based"
    file_size_mb: 15
    processing:
      harmonize_coords: false
      interpolation: "nearest_neighbor"  # For discrete to gridded conversion
    credentials_required: true
    accuracy:
      ph: "±0.01-0.02 pH units"
      coverage: "1M+ samples from 1000+ cruises"
    priority: 1
    
  cmems_nutrients:
    name: "CMEMS Ocean Biogeochemistry Nutrients (1993-2022)"
    description: "Historical daily biogeochemistry nutrients from CMEMS"
    product_id: "GLOBAL_MULTIYEAR_BGC_001_029"
    dataset_id: "cmems_mod_glo_bgc_my_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "1993-01-01"
      end: "2022-12-31"
      test_start: "1993-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["chl", "no3", "po4", "si", "o2", "nppv"]
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 25
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 2
    
  cmems_current_ph:
    name: "CMEMS Current Ocean Biogeochemistry with pH (2021-present)"
    description: "Current operational BGC data including pH from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-car_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["ph", "dissic", "talk"]  # Carbon variables only
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 20
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 3
    
  cmems_current_nutrients:
    name: "CMEMS Current Ocean Nutrients (2021-present)"
    description: "Current operational nutrient data from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-nut_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["fe", "no3", "po4", "si"]  # Nutrient variables only
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 15
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 4
    
  cmems_current_bio:
    name: "CMEMS Current Ocean Biology (2021-present)"
    description: "Current operational biological data from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-bio_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["nppv", "o2"]  # Biology variables only
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 10
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 5
    
  # Individual dataset configurations for direct access
  acidity_historical:
    name: "CMEMS Ocean Biogeochemistry Nutrients (1993-2022)"
    description: "Historical daily biogeochemistry nutrients from CMEMS"
    product_id: "GLOBAL_MULTIYEAR_BGC_001_029"
    dataset_id: "cmems_mod_glo_bgc_my_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "1993-01-01"
      end: "2022-12-31"
      test_start: "1993-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["chl", "no3", "po4", "si", "o2", "nppv"]
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 25
    processing:
      harmonize_coords: false
    credentials_required: true
    
  acidity_current:
    name: "CMEMS Current Ocean Biogeochemistry with pH (2021-present)"
    description: "Current operational BGC data including pH from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-car_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["ph", "dissic", "talk"]  # Carbon variables from car dataset
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 20
    processing:
      harmonize_coords: false
    credentials_required: true
    
  acidity:
    name: "Ocean Biogeochemistry (Multi-Source Hybrid: 1993-present)"
    description: "Comprehensive ocean chemistry combining GLODAP pH observations with CMEMS nutrients"
    hybrid_config: true
    data_sources:
      historical_ph: "glodap_ph"        # 1993-2021 discrete pH
      historical_nutrients: "cmems_nutrients"  # 1993-2022 daily nutrients  
      current_all: "cmems_current_ph"   # 2021-present daily pH + nutrients
    temporal_coverage:
      start: "1993-01-01"
      end: "present"
      test_start: "1993-01-01"
    spatial_resolution: "Multi-resolution (1°/0.25°)"
    coordinate_system: "-180-180"
    variables: ["ph", "ph_insitu", "talk", "dissic", "pco2", "no3", "po4", "si", "o2", "nppv"]
    data_types: ["discrete_samples", "continuous_gridded"]
    layers: ["surface"]
    update_frequency: "mixed"  # Discrete + daily
    processing:
      harmonize_coords: false
      merge_strategy: "spatial_temporal_interpolation"
    credentials_required: true
    advantages:
      - "True historical pH context from 1993"
      - "High-accuracy discrete pH measurements (±0.01-0.02)"
      - "Continuous daily nutrient context"
      - "Current operational pH data"
    limitations:
      - "pH data is discrete, not continuous"
      - "Spatial gaps in some ocean regions"
      - "Temporal resolution varies by data source"
    
  microplastics:
    name: "NOAA NCEI Marine Microplastics"
    description: "Marine Microplastics Observations Database"
    portal_url: "https://www.ncei.noaa.gov/products/microplastics"
    download_url: "https://www.ncei.noaa.gov/data/oceans/ncei/microplastics/export"
    temporal_coverage:
      start: "1972-04-01"
      end: "present"
      test_start: "1993-01-01"  # filter to match other datasets
    format: "csv"
    variables: ["concentration", "particle_count", "polymer_type", "size_class", "depth"]
    update_frequency: "weekly"  # check weekly, download if updated
    file_size_mb: 50  # approximate size
    processing:
      harmonize_coords: false
      filter_date_range: true
    
# Storage configuration
storage:
  base_path: "../ocean-data"
  raw_data_path: "raw"
  processed_data_path: "processed"
  logs_path: "logs"
  cache_path: "cache"
  max_storage_gb: 100  # warn if exceeded
  
# Download configuration
download:
  parallel_downloads: false  # Phase 1: sequential for stability
  max_retries: 3
  retry_delay_seconds: 5
  timeout_seconds: 300
  user_agent: "Ocean-Climate-Research/1.0 (panta-rhei-data-map)"
  
# Processing configuration
processing:
  temp_dir: "/tmp/ocean_data_processing"
  keep_temp_files: false
  compression_level: 4  # for NetCDF files