# Ocean Data Sources Configuration
# Defines data sources, URLs, and processing parameters for each dataset

datasets:
  sst:
    name: "NOAA OISST v2.1"
    description: "Sea Surface Temperature - Optimum Interpolation"
    base_url: "https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/"
    file_pattern: "oisst-avhrr-v02r01.{date}.nc"
    url_pattern: "{base_url}{year_month}/oisst-avhrr-v02r01.{date}.nc"
    temporal_coverage:
      start: "1981-09-01"
      end: "present"
      test_start: "2024-01-01"  # Start with 2024 for testing
    spatial_resolution: 0.25  # degrees
    target_resolution: 0.25   # native resolution - no artificial upsampling
    coordinate_system: "0-360"  # needs conversion to -180-180
    variables: ["sst", "anom", "err", "ice"]
    update_frequency: "daily"
    file_size_mb: 1.6  # approximate size per file
    processing:
      downsample: false          # disabled for ultra-high resolution textures
      harmonize_coords: true
    
  # Ultra-high resolution SST option for maximum texture quality
  sst_ultra:
    name: "NASA MUR SST v4.1"
    description: "Multi-scale Ultra-high Resolution (MUR) Sea Surface Temperature - 0.01° resolution"
    base_url: "https://podaac-opendap.jpl.nasa.gov/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/"
    file_pattern: "{year}/{day_of_year}/20240101090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc"
    url_pattern: "{base_url}{year}/{day_of_year}/20240101090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc"
    temporal_coverage:
      start: "2002-06-01"
      end: "present"
      test_start: "2024-01-01"
    spatial_resolution: 0.01  # degrees (100x better than standard SST)
    target_resolution: 0.01   # maintain ultra-high resolution
    coordinate_system: "-180-180"
    variables: ["analysed_sst", "analysis_error", "mask", "sea_ice_fraction"]
    update_frequency: "daily"
    file_size_mb: 150  # much larger due to high resolution
    processing:
      downsample: false
      harmonize_coords: false  # already in -180-180
    advantages:
      - "100x higher resolution than standard OISST"
      - "Superior coastal detail and feature resolution"
      - "NASA/JPL quality assurance"
      - "Global coverage with minimal gaps"
    credentials_required: false  # Public access via OPeNDAP
    priority: 1  # Preferred for ultra-high quality textures
    
  waves:
    name: "CMEMS Global Waves Analysis and Forecast"
    description: "Global Ocean Waves Analysis and Forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_WAV_001_027"
    dataset_id: "cmems_mod_glo_wav_anfc_0.083deg_PT3H-i"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "1993-01-01"
      end: "present"
      test_start: "2024-01-01"
    spatial_resolution: 0.083  # 1/12 degrees
    coordinate_system: "-180-180"
    variables: ["VHM0", "VMDR", "VTPK"]  # significant height, direction, period (actual CMEMS names)
    update_frequency: "daily"
    file_size_mb: 25  # approximate size per file
    processing:
      harmonize_coords: false  # already in -180-180
    credentials_required: true
    
  currents:
    name: "CMEMS Global Ocean Currents"
    description: "Global Ocean Physics Analysis and Forecast - Currents"
    product_id: "GLOBAL_ANALYSISFORECAST_PHY_001_024"
    dataset_id: "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2022-06-01"  # Updated based on CMEMS dataset availability
      end: "present"
      test_start: "2024-01-01"
    spatial_resolution: 0.083  # 1/12 degree
    coordinate_system: "-180-180"
    variables: ["uo", "vo"]  # zonal and meridional velocity
    layers: ["surface"]  # Phase 1: surface only
    update_frequency: "daily"
    file_size_mb: 15  # approximate size per file
    processing:
      harmonize_coords: false
    credentials_required: true
    
  # STRATEGIC HYBRID APPROACH: Historical + Current CMEMS
  # Combines historical biogeochemistry (1993-2022) with current operational data (2021-present)
  
  cmems_nutrients:
    name: "CMEMS Ocean Biogeochemistry Nutrients (1993-2022)"
    description: "Historical daily biogeochemistry nutrients from CMEMS"
    product_id: "GLOBAL_MULTIYEAR_BGC_001_029"
    dataset_id: "cmems_mod_glo_bgc_my_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "1993-01-01"
      end: "2022-12-31"
      test_start: "1993-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["chl", "no3", "po4", "si", "o2", "nppv"]
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 25
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 2
    
  cmems_current_ph:
    name: "CMEMS Current Ocean Biogeochemistry with pH (2021-present)"
    description: "Current operational BGC data including pH from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-car_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["ph", "dissic", "talk"]  # Carbon variables only
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 20
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 3
    
  cmems_current_nutrients:
    name: "CMEMS Current Ocean Nutrients (2021-present)"
    description: "Current operational nutrient data from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-nut_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["fe", "no3", "po4", "si"]  # Nutrient variables only
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 15
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 4
    
  cmems_current_bio:
    name: "CMEMS Current Ocean Biology (2021-present)"
    description: "Current operational biological data from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-bio_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["nppv", "o2"]  # Biology variables only
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 10
    processing:
      harmonize_coords: false
    credentials_required: true
    priority: 5
    
  # Individual dataset configurations for direct access
  acidity_historical:
    name: "CMEMS Ocean Biogeochemistry Nutrients (1993-2022)"
    description: "Historical daily biogeochemistry nutrients from CMEMS"
    product_id: "GLOBAL_MULTIYEAR_BGC_001_029"
    dataset_id: "cmems_mod_glo_bgc_my_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "1993-01-01"
      end: "2022-12-31"
      test_start: "1993-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["chl", "no3", "po4", "si", "o2", "nppv"]
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 25
    processing:
      harmonize_coords: false
    credentials_required: true
    
  acidity_current:
    name: "CMEMS Current Ocean Biogeochemistry with pH (2021-present)"
    description: "Current operational BGC data including pH from CMEMS forecast"
    product_id: "GLOBAL_ANALYSISFORECAST_BGC_001_028"
    dataset_id: "cmems_mod_glo_bgc-car_anfc_0.25deg_P1D-m"
    base_url: "https://data.marine.copernicus.eu"
    temporal_coverage:
      start: "2021-10-01"
      end: "present"
      test_start: "2023-01-01"
    spatial_resolution: 0.25  # degrees
    coordinate_system: "-180-180"
    variables: ["ph", "dissic", "talk"]  # Carbon variables from car dataset
    data_type: "continuous_gridded"
    layers: ["surface"]
    update_frequency: "daily"
    file_size_mb: 20
    processing:
      harmonize_coords: false
    credentials_required: true
    
  acidity:
    name: "Ocean Biogeochemistry (Multi-Source Hybrid: 1993-present)"
    description: "Comprehensive ocean chemistry combining GLODAP pH observations with CMEMS nutrients"
    hybrid_config: true
    data_sources:
      historical_ph: "acidity_historical"        # 1993-2022 historical biogeochemistry
      historical_nutrients: "acidity_historical"  # 1993-2022 daily nutrients  
      current_all: "acidity_current"   # 2021-present daily pH + nutrients
    temporal_coverage:
      start: "1993-01-01"
      end: "present"
      test_start: "1993-01-01"
    spatial_resolution: "Multi-resolution (1°/0.25°)"
    coordinate_system: "-180-180"
    variables: ["ph", "ph_insitu", "talk", "dissic", "pco2", "no3", "po4", "si", "o2", "nppv"]
    data_types: ["discrete_samples", "continuous_gridded"]
    layers: ["surface"]
    update_frequency: "mixed"  # Discrete + daily
    processing:
      harmonize_coords: false
      merge_strategy: "spatial_temporal_interpolation"
    credentials_required: true
    advantages:
      - "True historical pH context from 1993"
      - "High-accuracy discrete pH measurements (±0.01-0.02)"
      - "Continuous daily nutrient context"
      - "Current operational pH data"
    limitations:
      - "pH data is discrete, not continuous"
      - "Spatial gaps in some ocean regions"
      - "Temporal resolution varies by data source"
    
  microplastics:
    name: "NOAA NCEI Marine Microplastics"
    description: "Marine Microplastics Observations Database"
    portal_url: "https://www.ncei.noaa.gov/products/microplastics"
    download_url: "https://www.ncei.noaa.gov/data/oceans/ncei/microplastics/export"
    temporal_coverage:
      start: "1972-04-01"
      end: "present"
      test_start: "1993-01-01"  # filter to match other datasets
    format: "csv"
    variables: ["concentration", "particle_count", "polymer_type", "size_class", "depth"]
    update_frequency: "weekly"  # check weekly, download if updated
    file_size_mb: 50  # approximate size
    processing:
      harmonize_coords: false
      filter_date_range: true
    
# Storage configuration
storage:
  base_path: "../ocean-data"
  raw_data_path: "raw"
  processed_data_path: "processed"
  logs_path: "logs"
  cache_path: "cache"
  max_storage_gb: 100  # warn if exceeded
  
# Download configuration
download:
  parallel_downloads: false  # Phase 1: sequential for stability
  max_retries: 3
  retry_delay_seconds: 5
  timeout_seconds: 300
  user_agent: "Ocean-Climate-Research/1.0 (panta-rhei-data-map)"
  
# Processing configuration
processing:
  temp_dir: "/tmp/ocean_data_processing"
  keep_temp_files: false
  compression_level: 4  # for NetCDF files